name: Build and Push Docker Image

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  Azure-login:
    runs-on: ubuntu-latest
    steps:
     - name: Log in to Azure CLI 
       uses: azure/login@v1 
       with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
         # enable-AzPSSession: true
     - name: Build and tag Docker image
       run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/vilas:${{ github.sha }} .

     - name: Push Docker image to ACR
       run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vilas:${{ github.sha }}
